### ISSUE TITLE
PlayerDB and Hypixel APIs should be called with unique CONFIG headers.

### ISSUE THREAD

**Issue by StinkyDubeau** [StinkyDubeau/pixelstats#4]
PlayerDB is currently receiving the API key for hypixel. This is bad.

Less bad, but still incorrectly, hypixel is recieving the user-agent intended for PlayerDB.

To fix, each API should have its own config object instead of sharing one as it does now:

```
const CONFIG = {
    headers: {
        "API-Key": KEY,
        "user-agent": `github.com/stinkydubeau/${PROJECTNAME}`,
    }
}
```

**Comment by devloves** [comment]
I can assist in this

**Comment by StinkyDubeau** [comment]
> I can assist in this

That would be great Devansh. Please give it a go and make a pull request. I’ll review & merge!

**Comment by StinkyDubeau** [comment]
Thanks for your help Devansh and sorry for leaving this open for so long!
